% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Trabajo de Evaluación Continua de Modelos de Regresión},
  pdfauthor={Xiana Carrera Alonso, Pablo Díaz Viñambres},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Trabajo de Evaluación Continua de Modelos de Regresión}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Curso 2021/2022}
\author{Xiana Carrera Alonso, Pablo Díaz Viñambres}
\date{}

\begin{document}
\maketitle

\hypertarget{r-markdown}{%
\subsection{R Markdown}\label{r-markdown}}

Poner introducción aquí

o tablas:

\begin{center}
\begin{tabular}{ |c c c| }
 \hline
 celda1 & celda2 & celda3 \\
 \hline
 celda4 & celda5 & celda6 \\  
 celda7 & celda8 & celda9 \\   
  \hline
\end{tabular}
\end{center}

\hypertarget{introducciuxf3n}{%
\section{Introducción}\label{introducciuxf3n}}

En el siguiente informe se hará un estudio estadístico en el que se
analizará la influencia de la variable X sobre la variable Y, en el
marco de la regresión lineal.

\hypertarget{libreruxedas-utilizadas}{%
\subsection{Librerías utilizadas}\label{libreruxedas-utilizadas}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)      }\CommentTok{\# Para diagrama de dispersión con región de confianza}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'ggplot2' was built under R version 4.1.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lmtest)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'lmtest' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## Loading required package: zoo
\end{verbatim}

\begin{verbatim}
## Warning: package 'zoo' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'zoo'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     as.Date, as.Date.numeric
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(sm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'sm' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## Package 'sm', version 2.2-5.7: type help(sm) for summary information
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(rpanel)   }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'rpanel' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## Loading required package: tcltk
\end{verbatim}

\begin{verbatim}
## Package `rpanel', version 1.1-5: type help(rpanel) for summary information
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(viridis)      }\CommentTok{\# Para gradiente de colores en gráfica de normalidad}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'viridis' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## Loading required package: viridisLite
\end{verbatim}

\begin{verbatim}
## Warning: package 'viridisLite' was built under R version 4.1.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(nortest)      }\CommentTok{\# Necesario para lillie.test}
\FunctionTok{library}\NormalTok{(car)          }\CommentTok{\# Necesario para QQPlot}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: carData
\end{verbatim}

\begin{verbatim}
## Warning: package 'carData' was built under R version 4.1.3
\end{verbatim}

\hypertarget{lectura-de-datos}{%
\subsection{Lectura de datos}\label{lectura-de-datos}}

Asimismo, leemos el número de datos n.

En primer lugar, leemos los datos del archivo proporcionado, que cuenta
con 76 variables respuesta, Y1, \ldots, Y76, y una variable explicativa
común, X. En nuestro caso, limitaremos el estudio a Y47, que denotaremos
sencillamente como Y de aquí en adelante.

Nada más importar el archivo (para lo cual es necesario que el usuario
cambie el directorio actual, empleando, por ejemplo, \emph{setwd} o
\emph{Ctrl + May + H}), realizamos un pequeño análisis estadístico de
los datos empleando las funciones estándar \emph{head}, \emph{class},
\emph{names}, \emph{str} y \emph{summary}.

Por comodidad para cálculos posteriores, también guardamos el número de
datos, n.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) \# Configurar wd a la carpeta actual (solo en RStudio) }
\CommentTok{\# Ejemplo de uso de setwd para cambiar el directorio actual:}
\CommentTok{\#setwd("C:\textbackslash{}\textbackslash{}Users\textbackslash{}\textbackslash{}Pablo\textbackslash{}\textbackslash{}Desktop\textbackslash{}\textbackslash{}IE\_Regresion")}

\CommentTok{\# Leemos los datos empleando read.table (por la extensión .txt)}
\CommentTok{\# Indicamos que existe una cabecera, que las columnas están separadas por espacios y que el signo decimal es el punto.}
\NormalTok{datos }\OtherTok{\textless{}{-}} \FunctionTok{read.table}\NormalTok{(}\StringTok{"datos\_trabajo\_temas6y7.txt"}\NormalTok{, }\AttributeTok{header=}\NormalTok{T, }\AttributeTok{sep=}\StringTok{" "}\NormalTok{, }\AttributeTok{dec=}\StringTok{"."}\NormalTok{)}
\CommentTok{\# Comprobamos la estructura de las primeras filas}
\FunctionTok{head}\NormalTok{(datos)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       Y1      Y2      Y3      Y4     Y5      Y6       Y7      Y8      Y9    Y10
## 1 2.7936  1.4752 -1.4537  0.1194 0.8976  2.2824  -0.3421  8.3449  2.6926 0.2066
## 2 9.7720 -5.6849  5.9324 -5.8971 6.7202 12.8063  -6.8206 -6.8406 24.8270 4.9308
## 3 7.0580 -6.6688  6.5421 -4.4595 6.8422  1.9432  -1.8182 -2.2344 29.5625 6.0275
## 4 6.5642 -4.7374  3.6894 -4.6314 7.8882  8.2429  -3.6053 -6.6413 20.7592 7.6040
## 5 9.6015 -7.7211  8.4552 -7.6432 9.4562 13.0013  -5.1338 -1.8076 38.6192 7.6951
## 6 9.1802 -5.6075  5.7340 -6.1928 5.9942  7.3444 -13.0044 -3.5044 18.2656 6.2518
##      Y11     Y12     Y13     Y14     Y15     Y16     Y17     Y18      Y19
## 1 3.0180  1.1751  8.4093  9.8550 -0.4541  0.4048 -2.0111  3.8622  -0.8111
## 2 6.3933 -5.9441 11.7228 23.4858 -5.9780  8.1232 -4.6495  7.7169 -10.2109
## 3 7.3119 -4.5747 13.3034 22.5277 -7.4146  9.0688 -5.5802  8.7706 -11.8967
## 4 8.0416 -4.2717 10.9460 20.9227 -7.8371  8.6477 -3.6450  9.3550  -6.1172
## 5 9.9560 -6.9841 14.3346 16.1194 -8.0503 11.5215 -7.0518 14.5981 -17.8672
## 6 8.8719 -6.4898 11.9024 14.1177 -4.8284 10.3868 -3.5018 10.0539 -10.5218
##      Y20     Y21     Y22     Y23     Y24    Y25     Y26      Y27     Y28
## 1 3.2525  3.6851  1.4066 -1.5791 23.1095 1.0566  2.4127  -2.3566  8.6631
## 2 7.0330 11.3887 -8.0260 -5.4715 43.5835 6.6822 14.4174 -13.7691 20.1870
## 3 6.0840  9.8021 -4.5552  0.7662 40.1477 5.7555 13.4886 -10.7275 17.4628
## 4 6.3954  6.7942 -2.0075 -7.7817 41.9463 5.9666 16.0072 -11.0726 16.0018
## 5 7.6931 15.2457 -2.0352 -7.6959 58.3724 8.6102 19.6299 -13.0778 21.9418
## 6 8.6100 10.4684 -2.0878 -0.1977 38.1193 5.4019 15.6906 -11.0560 17.2514
##       Y29      Y30     Y31     Y32     Y33      Y34    Y35     Y36     Y37
## 1 22.7469  -2.4220  3.5571  1.8961  0.0066   1.7376 2.1588  4.0657  1.3298
## 2 30.2249 -16.1472  8.2697 -4.0607 21.0551 -14.1993 7.6442 11.3337 -5.4907
## 3 24.0192 -13.2535  8.9133 -3.2104 15.3934 -20.2062 6.4781  0.8821 -6.3081
## 4 20.5644 -12.6253 10.2436 -3.9753 16.9404 -12.0525 6.1412 16.9086  1.6349
## 5 30.3645 -15.7150 11.6328 -6.0175 24.9262 -25.0584 8.0722 20.3899 -1.2564
## 6 28.3363 -11.9880  8.7541 -3.7809 18.2787 -13.3801 5.0839 11.0259 -1.1167
##       Y38      Y39     Y40     Y41      Y42     Y43     Y44      Y45     Y46
## 1  6.4494  -1.2899 -0.6144  5.8854   1.0759  6.5516 12.2680  -3.2194  3.9002
## 2 -4.5418  62.1693  6.6262 20.0729 -16.4415 25.0951 39.1833 -21.9718 10.5971
## 3 -3.6508  66.1270  6.7749 12.7528 -16.8969 20.6230 31.8153 -21.7585  9.9867
## 4  0.0321  63.9750  5.8612 22.9456 -21.7783 25.9051 35.9875 -18.2197 10.3999
## 5 -3.6769 109.1664  8.4507 26.7306 -25.0174 37.9203 47.3905 -23.7512 13.2672
## 6 -8.0320  60.2133  6.2397 15.6328 -20.7705 25.9365 32.7206 -16.5978 10.5171
##       Y47     Y48      Y49    Y50     Y51      Y52     Y53      Y54    Y55
## 1  1.4567  8.8645  -1.1170 2.3795  5.0323   3.3162  0.6895  -5.9556 2.4969
## 2 -1.2109 17.1167 -22.5165 6.4156 10.7858  -0.7594 -5.0630  77.7399 6.0267
## 3 -2.1529 17.6692 -11.5372 7.3901  1.3646   0.3152 -8.4656  77.1477 7.8546
## 4 -2.1343 25.0218 -21.7804 6.5836  4.5108  -0.3765 -2.9016  90.0764 5.7428
## 5 -4.9584 27.1666 -29.8614 9.1737  4.6134 -13.0519 -8.6802 126.6687 8.4139
## 6 -1.3663 17.7839 -20.2871 5.5370 13.4254  -2.6063 -4.0223  49.2404 6.3436
##       Y56      Y57     Y58     Y59      Y60     Y61     Y62     Y63      Y64
## 1  3.7127  -2.4819  4.5862 44.3813  -9.5253  6.5714  3.2692 -1.7145  -1.6168
## 2 23.2494 -22.3551 38.2988 57.6196 -22.5788 12.5265  0.2058 20.2873 -19.4924
## 3 28.1697 -22.5717 28.9487 34.4986 -23.8544 10.4411 -0.3878 24.2690 -23.6455
## 4 25.2633 -20.9713 26.6047 41.0510 -21.0315 11.2169 -2.9589 33.4181 -25.6653
## 5 37.0260 -31.3867 34.4175 68.6210 -28.3239 13.0415 -2.6899 47.3101 -33.9286
## 6 30.3660 -24.0677 27.4447 37.6048 -25.3962 10.2760 -1.1854 24.9994 -31.4601
##      Y65     Y66     Y67     Y68      Y69    Y70     Y71      Y72     Y73
## 1 1.8847  5.5941  3.0926  4.1399 -19.1810 1.0801  8.6350  -8.5187  3.9191
## 2 6.2252 13.4508 -6.0011 -4.8800  83.7734 4.9470 26.9301 -33.3999 34.6876
## 3 6.8574  7.1768 -0.2933 -3.8193 123.9641 6.0652 33.6126 -27.2912 29.2082
## 4 6.5760  5.3684  1.0325 -6.8934  83.6935 5.2763 30.2013 -32.7018 40.2327
## 5 8.8142 15.7666 -8.4158 -5.8817 186.4314 9.6777 44.7807 -35.8710 42.3833
## 6 6.7634 16.3575 -2.3546 -5.1990  95.2365 6.2355 21.9198 -30.3876 32.5226
##       Y74      Y75     Y76      X
## 1 21.5076   1.6372  5.8789 1.1370
## 2 43.5076 -30.4974 12.7668 6.2230
## 3 45.2820 -32.0879 11.5578 6.0927
## 4 64.9294 -33.1266 11.0957 6.2338
## 5 70.0942 -40.3019 12.8412 8.6092
## 6 49.3564 -31.8837 11.6881 6.4031
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Comprobamos que el objeto resultante es un data.frame}
\FunctionTok{class}\NormalTok{(datos)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "data.frame"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Vemos los nombres de las variables}
\FunctionTok{names}\NormalTok{(datos)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "Y1"  "Y2"  "Y3"  "Y4"  "Y5"  "Y6"  "Y7"  "Y8"  "Y9"  "Y10" "Y11" "Y12"
## [13] "Y13" "Y14" "Y15" "Y16" "Y17" "Y18" "Y19" "Y20" "Y21" "Y22" "Y23" "Y24"
## [25] "Y25" "Y26" "Y27" "Y28" "Y29" "Y30" "Y31" "Y32" "Y33" "Y34" "Y35" "Y36"
## [37] "Y37" "Y38" "Y39" "Y40" "Y41" "Y42" "Y43" "Y44" "Y45" "Y46" "Y47" "Y48"
## [49] "Y49" "Y50" "Y51" "Y52" "Y53" "Y54" "Y55" "Y56" "Y57" "Y58" "Y59" "Y60"
## [61] "Y61" "Y62" "Y63" "Y64" "Y65" "Y66" "Y67" "Y68" "Y69" "Y70" "Y71" "Y72"
## [73] "Y73" "Y74" "Y75" "Y76" "X"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Comprobamos la estructura de los datos}
\FunctionTok{str}\NormalTok{(datos)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    120 obs. of  77 variables:
##  $ Y1 : num  2.79 9.77 7.06 6.56 9.6 ...
##  $ Y2 : num  1.48 -5.68 -6.67 -4.74 -7.72 ...
##  $ Y3 : num  -1.45 5.93 6.54 3.69 8.46 ...
##  $ Y4 : num  0.119 -5.897 -4.46 -4.631 -7.643 ...
##  $ Y5 : num  0.898 6.72 6.842 7.888 9.456 ...
##  $ Y6 : num  2.28 12.81 1.94 8.24 13 ...
##  $ Y7 : num  -0.342 -6.821 -1.818 -3.605 -5.134 ...
##  $ Y8 : num  8.34 -6.84 -2.23 -6.64 -1.81 ...
##  $ Y9 : num  2.69 24.83 29.56 20.76 38.62 ...
##  $ Y10: num  0.207 4.931 6.027 7.604 7.695 ...
##  $ Y11: num  3.02 6.39 7.31 8.04 9.96 ...
##  $ Y12: num  1.18 -5.94 -4.57 -4.27 -6.98 ...
##  $ Y13: num  8.41 11.72 13.3 10.95 14.33 ...
##  $ Y14: num  9.86 23.49 22.53 20.92 16.12 ...
##  $ Y15: num  -0.454 -5.978 -7.415 -7.837 -8.05 ...
##  $ Y16: num  0.405 8.123 9.069 8.648 11.521 ...
##  $ Y17: num  -2.01 -4.65 -5.58 -3.64 -7.05 ...
##  $ Y18: num  3.86 7.72 8.77 9.36 14.6 ...
##  $ Y19: num  -0.811 -10.211 -11.897 -6.117 -17.867 ...
##  $ Y20: num  3.25 7.03 6.08 6.4 7.69 ...
##  $ Y21: num  3.69 11.39 9.8 6.79 15.25 ...
##  $ Y22: num  1.41 -8.03 -4.56 -2.01 -2.04 ...
##  $ Y23: num  -1.579 -5.471 0.766 -7.782 -7.696 ...
##  $ Y24: num  23.1 43.6 40.1 41.9 58.4 ...
##  $ Y25: num  1.06 6.68 5.76 5.97 8.61 ...
##  $ Y26: num  2.41 14.42 13.49 16.01 19.63 ...
##  $ Y27: num  -2.36 -13.77 -10.73 -11.07 -13.08 ...
##  $ Y28: num  8.66 20.19 17.46 16 21.94 ...
##  $ Y29: num  22.7 30.2 24 20.6 30.4 ...
##  $ Y30: num  -2.42 -16.15 -13.25 -12.63 -15.71 ...
##  $ Y31: num  3.56 8.27 8.91 10.24 11.63 ...
##  $ Y32: num  1.9 -4.06 -3.21 -3.98 -6.02 ...
##  $ Y33: num  0.0066 21.0551 15.3934 16.9404 24.9262 ...
##  $ Y34: num  1.74 -14.2 -20.21 -12.05 -25.06 ...
##  $ Y35: num  2.16 7.64 6.48 6.14 8.07 ...
##  $ Y36: num  4.066 11.334 0.882 16.909 20.39 ...
##  $ Y37: num  1.33 -5.49 -6.31 1.63 -1.26 ...
##  $ Y38: num  6.4494 -4.5418 -3.6508 0.0321 -3.6769 ...
##  $ Y39: num  -1.29 62.17 66.13 63.98 109.17 ...
##  $ Y40: num  -0.614 6.626 6.775 5.861 8.451 ...
##  $ Y41: num  5.89 20.07 12.75 22.95 26.73 ...
##  $ Y42: num  1.08 -16.44 -16.9 -21.78 -25.02 ...
##  $ Y43: num  6.55 25.1 20.62 25.91 37.92 ...
##  $ Y44: num  12.3 39.2 31.8 36 47.4 ...
##  $ Y45: num  -3.22 -21.97 -21.76 -18.22 -23.75 ...
##  $ Y46: num  3.9 10.6 9.99 10.4 13.27 ...
##  $ Y47: num  1.46 -1.21 -2.15 -2.13 -4.96 ...
##  $ Y48: num  8.86 17.12 17.67 25.02 27.17 ...
##  $ Y49: num  -1.12 -22.52 -11.54 -21.78 -29.86 ...
##  $ Y50: num  2.38 6.42 7.39 6.58 9.17 ...
##  $ Y51: num  5.03 10.79 1.36 4.51 4.61 ...
##  $ Y52: num  3.316 -0.759 0.315 -0.376 -13.052 ...
##  $ Y53: num  0.69 -5.06 -8.47 -2.9 -8.68 ...
##  $ Y54: num  -5.96 77.74 77.15 90.08 126.67 ...
##  $ Y55: num  2.5 6.03 7.85 5.74 8.41 ...
##  $ Y56: num  3.71 23.25 28.17 25.26 37.03 ...
##  $ Y57: num  -2.48 -22.36 -22.57 -20.97 -31.39 ...
##  $ Y58: num  4.59 38.3 28.95 26.6 34.42 ...
##  $ Y59: num  44.4 57.6 34.5 41.1 68.6 ...
##  $ Y60: num  -9.53 -22.58 -23.85 -21.03 -28.32 ...
##  $ Y61: num  6.57 12.53 10.44 11.22 13.04 ...
##  $ Y62: num  3.269 0.206 -0.388 -2.959 -2.69 ...
##  $ Y63: num  -1.71 20.29 24.27 33.42 47.31 ...
##  $ Y64: num  -1.62 -19.49 -23.65 -25.67 -33.93 ...
##  $ Y65: num  1.88 6.23 6.86 6.58 8.81 ...
##  $ Y66: num  5.59 13.45 7.18 5.37 15.77 ...
##  $ Y67: num  3.093 -6.001 -0.293 1.032 -8.416 ...
##  $ Y68: num  4.14 -4.88 -3.82 -6.89 -5.88 ...
##  $ Y69: num  -19.2 83.8 124 83.7 186.4 ...
##  $ Y70: num  1.08 4.95 6.07 5.28 9.68 ...
##  $ Y71: num  8.63 26.93 33.61 30.2 44.78 ...
##  $ Y72: num  -8.52 -33.4 -27.29 -32.7 -35.87 ...
##  $ Y73: num  3.92 34.69 29.21 40.23 42.38 ...
##  $ Y74: num  21.5 43.5 45.3 64.9 70.1 ...
##  $ Y75: num  1.64 -30.5 -32.09 -33.13 -40.3 ...
##  $ Y76: num  5.88 12.77 11.56 11.1 12.84 ...
##  $ X  : num  1.14 6.22 6.09 6.23 8.61 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Y realizamos un pequeño análisis estadístico}
\FunctionTok{summary}\NormalTok{(datos)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        Y1                Y2                Y3                Y4         
##  Min.   :-0.2477   Min.   :-9.4897   Min.   :-2.1023   Min.   :-9.1588  
##  1st Qu.: 3.0484   1st Qu.:-5.7411   1st Qu.: 0.6724   1st Qu.:-5.9943  
##  Median : 5.0805   Median :-2.7276   Median : 2.9093   Median :-2.7178  
##  Mean   : 5.3895   Mean   :-3.2972   Mean   : 3.2825   Mean   :-3.2029  
##  3rd Qu.: 7.5942   3rd Qu.:-0.9511   3rd Qu.: 5.7836   3rd Qu.:-0.5092  
##  Max.   :11.8944   Max.   : 2.4110   Max.   :10.4587   Max.   : 2.4227  
##        Y5                Y6               Y7                 Y8          
##  Min.   :-0.7795   Min.   :-1.866   Min.   :-14.3113   Min.   :-11.0489  
##  1st Qu.: 1.6522   1st Qu.: 2.270   1st Qu.: -5.2127   1st Qu.: -4.1702  
##  Median : 3.8990   Median : 4.546   Median : -2.3262   Median : -0.8625  
##  Mean   : 4.3346   Mean   : 5.418   Mean   : -3.2343   Mean   : -1.2905  
##  3rd Qu.: 6.5736   3rd Qu.: 7.871   3rd Qu.: -0.1593   3rd Qu.:  1.4933  
##  Max.   :10.9457   Max.   :21.604   Max.   :  6.7544   Max.   :  8.3449  
##        Y9              Y10               Y11               Y12          
##  Min.   :-1.829   Min.   :-0.8901   Min.   :-0.2592   Min.   :-10.4924  
##  1st Qu.: 6.989   1st Qu.: 1.7983   1st Qu.: 2.8566   1st Qu.: -5.4696  
##  Median :13.039   Median : 4.2346   Median : 5.1034   Median : -2.2569  
##  Mean   :16.112   Mean   : 4.3589   Mean   : 5.2499   Mean   : -3.1751  
##  3rd Qu.:23.215   3rd Qu.: 6.4514   3rd Qu.: 7.8987   3rd Qu.: -0.7196  
##  Max.   :43.531   Max.   :10.7299   Max.   :10.8283   Max.   :  2.5404  
##       Y13              Y14              Y15               Y16         
##  Min.   : 4.138   Min.   : 6.574   Min.   :-10.381   Min.   : 0.4048  
##  1st Qu.: 6.980   1st Qu.:10.931   1st Qu.: -6.495   1st Qu.: 3.8066  
##  Median : 8.796   Median :13.473   Median : -3.727   Median : 5.6679  
##  Mean   : 9.279   Mean   :14.015   Mean   : -4.190   Mean   : 6.3914  
##  3rd Qu.:11.422   3rd Qu.:16.799   3rd Qu.: -1.598   3rd Qu.: 9.1575  
##  Max.   :16.136   Max.   :23.486   Max.   :  1.400   Max.   :12.9407  
##       Y17               Y18              Y19               Y20        
##  Min.   :-8.7036   Min.   :-4.973   Min.   :-19.249   Min.   :-1.422  
##  1st Qu.:-4.8080   1st Qu.: 1.843   1st Qu.:-11.477   1st Qu.: 2.304  
##  Median :-2.2672   Median : 6.061   Median : -5.399   Median : 3.688  
##  Mean   :-2.3692   Mean   : 6.351   Mean   : -6.473   Mean   : 4.314  
##  3rd Qu.: 0.3271   3rd Qu.:11.011   3rd Qu.: -1.515   3rd Qu.: 6.573  
##  Max.   : 4.3058   Max.   :20.155   Max.   :  4.032   Max.   :10.490  
##       Y21               Y22                Y23              Y24        
##  Min.   : 0.7946   Min.   :-18.4719   Min.   :-9.925   Min.   :-9.932  
##  1st Qu.: 3.2239   1st Qu.: -4.5732   1st Qu.:-5.144   1st Qu.: 9.515  
##  Median : 5.0702   Median : -1.4525   Median :-1.068   Median :21.659  
##  Mean   : 6.3172   Mean   : -2.5908   Mean   :-1.430   Mean   :28.843  
##  3rd Qu.: 8.2181   3rd Qu.:  0.6842   3rd Qu.: 2.182   3rd Qu.:46.626  
##  Max.   :18.1741   Max.   :  5.6872   Max.   : 7.590   Max.   :92.268  
##       Y25              Y26              Y27               Y28        
##  Min.   :-2.223   Min.   :-2.213   Min.   :-21.125   Min.   : 3.714  
##  1st Qu.: 1.915   1st Qu.: 4.587   1st Qu.:-12.480   1st Qu.: 8.816  
##  Median : 3.854   Median : 7.980   Median : -7.104   Median :12.078  
##  Mean   : 4.288   Mean   : 9.530   Mean   : -7.484   Mean   :13.260  
##  3rd Qu.: 6.531   3rd Qu.:14.420   3rd Qu.: -2.084   3rd Qu.:17.261  
##  Max.   :10.695   Max.   :20.826   Max.   :  3.126   Max.   :24.713  
##       Y29              Y30               Y31              Y32         
##  Min.   : 7.941   Min.   :-21.329   Min.   : 1.422   Min.   :-7.0392  
##  1st Qu.:17.240   1st Qu.:-13.804   1st Qu.: 4.783   1st Qu.:-3.7479  
##  Median :22.875   Median : -7.595   Median : 6.683   Median :-0.5868  
##  Mean   :23.859   Mean   : -8.606   Mean   : 7.209   Mean   :-1.2995  
##  3rd Qu.:29.656   3rd Qu.: -3.494   3rd Qu.: 9.472   3rd Qu.: 1.0191  
##  Max.   :50.584   Max.   :  1.947   Max.   :13.591   Max.   : 4.2334  
##       Y33              Y34               Y35              Y36         
##  Min.   :-7.728   Min.   :-28.198   Min.   :-2.408   Min.   : 0.2674  
##  1st Qu.: 1.371   1st Qu.:-15.426   1st Qu.: 2.034   1st Qu.: 4.0594  
##  Median : 7.525   Median : -8.321   Median : 3.588   Median : 6.3597  
##  Mean   : 9.261   Mean   : -9.564   Mean   : 4.239   Mean   : 7.0433  
##  3rd Qu.:17.133   3rd Qu.: -2.240   3rd Qu.: 6.788   3rd Qu.: 9.2219  
##  Max.   :28.809   Max.   :  6.655   Max.   :10.742   Max.   :20.3899  
##       Y37                Y38               Y39               Y40        
##  Min.   :-15.1027   Min.   :-11.146   Min.   : -3.547   Min.   :-1.478  
##  1st Qu.: -2.5464   1st Qu.: -4.271   1st Qu.: 12.994   1st Qu.: 1.958  
##  Median :  0.1824   Median : -1.122   Median : 33.292   Median : 4.036  
##  Mean   : -0.8192   Mean   : -1.620   Mean   : 43.782   Mean   : 4.396  
##  3rd Qu.:  1.7337   3rd Qu.:  1.098   3rd Qu.: 68.176   3rd Qu.: 6.805  
##  Max.   :  4.3262   Max.   :  6.449   Max.   :136.722   Max.   :10.735  
##       Y41              Y42               Y43               Y44        
##  Min.   :-7.186   Min.   :-31.783   Min.   :-0.7223   Min.   : 9.775  
##  1st Qu.: 7.086   1st Qu.:-17.317   1st Qu.: 9.6409   1st Qu.:23.755  
##  Median :12.739   Median :-10.253   Median :16.1155   Median :31.898  
##  Mean   :13.523   Mean   :-11.593   Mean   :17.3573   Mean   :32.008  
##  3rd Qu.:21.354   3rd Qu.: -4.772   3rd Qu.:25.1589   3rd Qu.:39.326  
##  Max.   :31.027   Max.   :  7.163   Max.   :37.9203   Max.   :63.723  
##       Y45               Y46              Y47               Y48        
##  Min.   :-30.379   Min.   : 3.455   Min.   :-7.0839   Min.   :-5.669  
##  1st Qu.:-20.006   1st Qu.: 5.991   1st Qu.:-2.4687   1st Qu.: 3.989  
##  Median :-11.557   Median : 7.841   Median : 0.1661   Median :12.319  
##  Mean   :-12.766   Mean   : 8.315   Mean   :-0.1815   Mean   :13.861  
##  3rd Qu.: -5.239   3rd Qu.:10.537   3rd Qu.: 2.3278   3rd Qu.:23.917  
##  Max.   :  3.775   Max.   :14.261   Max.   : 5.9654   Max.   :38.238  
##       Y49               Y50               Y51              Y52         
##  Min.   :-36.180   Min.   :-0.8581   Min.   : 1.365   Min.   :-14.871  
##  1st Qu.:-21.109   1st Qu.: 2.0911   1st Qu.: 4.943   1st Qu.: -2.533  
##  Median :-11.047   Median : 3.8673   Median : 6.649   Median :  0.872  
##  Mean   :-12.865   Mean   : 4.3877   Mean   : 8.586   Mean   : -0.389  
##  3rd Qu.: -2.041   3rd Qu.: 6.7008   3rd Qu.:12.362   3rd Qu.:  2.842  
##  Max.   :  6.676   Max.   :10.5254   Max.   :25.002   Max.   :  5.006  
##       Y53               Y54              Y55               Y56        
##  Min.   :-10.383   Min.   :-14.72   Min.   :-0.9298   Min.   :-3.889  
##  1st Qu.: -4.030   1st Qu.: 16.51   1st Qu.: 1.6218   1st Qu.: 8.417  
##  Median : -1.738   Median : 39.72   Median : 3.5498   Median :15.384  
##  Mean   : -1.451   Mean   : 55.65   Mean   : 4.1061   Mean   :18.391  
##  3rd Qu.:  1.187   3rd Qu.: 86.76   3rd Qu.: 6.8756   3rd Qu.:28.227  
##  Max.   :  7.928   Max.   :195.65   Max.   :10.1064   Max.   :45.738  
##       Y57               Y58               Y59             Y60        
##  Min.   :-42.630   Min.   : 0.1507   Min.   :11.16   Min.   :-41.59  
##  1st Qu.:-24.336   1st Qu.:11.5121   1st Qu.:27.56   1st Qu.:-26.61  
##  Median :-14.001   Median :20.0358   Median :41.77   Median :-14.08  
##  Mean   :-15.735   Mean   :22.2223   Mean   :43.05   Mean   :-17.26  
##  3rd Qu.: -5.564   3rd Qu.:33.8884   3rd Qu.:54.77   3rd Qu.: -6.92  
##  Max.   :  8.046   Max.   :55.7775   Max.   :97.85   Max.   :  4.94  
##       Y61              Y62               Y63               Y64         
##  Min.   : 3.246   Min.   :-4.6786   Min.   :-16.123   Min.   :-46.083  
##  1st Qu.: 6.560   1st Qu.:-1.8111   1st Qu.:  4.627   1st Qu.:-28.714  
##  Median : 8.561   Median : 1.0312   Median : 13.647   Median :-13.595  
##  Mean   : 9.141   Mean   : 0.8388   Mean   : 16.574   Mean   :-16.909  
##  3rd Qu.:11.588   3rd Qu.: 3.4876   3rd Qu.: 27.989   3rd Qu.: -5.593  
##  Max.   :15.708   Max.   : 6.1329   Max.   : 53.417   Max.   :  9.246  
##       Y65              Y66              Y67                Y68         
##  Min.   :-1.674   Min.   : 1.439   Min.   :-12.7320   Min.   :-12.656  
##  1st Qu.: 1.561   1st Qu.: 6.403   1st Qu.: -1.7827   1st Qu.: -4.001  
##  Median : 3.826   Median : 8.417   Median :  1.8860   Median : -1.635  
##  Mean   : 4.314   Mean   : 8.997   Mean   :  0.8352   Mean   : -1.548  
##  3rd Qu.: 6.787   3rd Qu.:10.678   3rd Qu.:  3.8491   3rd Qu.:  1.265  
##  Max.   :10.992   Max.   :18.891   Max.   :  6.3926   Max.   :  6.570  
##       Y69              Y70              Y71              Y72         
##  Min.   :-19.18   Min.   :-1.064   Min.   :-6.198   Min.   :-54.773  
##  1st Qu.: 19.91   1st Qu.: 2.043   1st Qu.: 9.681   1st Qu.:-32.094  
##  Median : 48.11   Median : 3.807   Median :18.659   Median :-15.862  
##  Mean   : 68.49   Mean   : 4.330   Mean   :21.680   Mean   :-19.948  
##  3rd Qu.:101.87   3rd Qu.: 6.860   3rd Qu.:33.659   3rd Qu.: -7.352  
##  Max.   :220.42   Max.   :11.401   Max.   :56.576   Max.   :  3.507  
##       Y73              Y74              Y75               Y76        
##  Min.   :-4.935   Min.   : 14.30   Min.   :-56.984   Min.   : 4.809  
##  1st Qu.:12.821   1st Qu.: 35.79   1st Qu.:-33.665   1st Qu.: 7.861  
##  Median :23.417   Median : 45.85   Median :-19.400   Median : 9.875  
##  Mean   :24.692   Mean   : 49.42   Mean   :-21.114   Mean   :10.239  
##  3rd Qu.:36.956   3rd Qu.: 64.77   3rd Qu.: -7.322   3rd Qu.:12.595  
##  Max.   :58.703   Max.   :109.29   Max.   :  5.546   Max.   :16.729  
##        X        
##  Min.   :0.095  
##  1st Qu.:1.795  
##  Median :3.232  
##  Mean   :4.268  
##  3rd Qu.:6.667  
##  Max.   :9.921
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Seleccionamos las dos variables de interés}
\NormalTok{X }\OtherTok{\textless{}{-}}\NormalTok{ datos[,}\StringTok{"X"}\NormalTok{]}
\NormalTok{Y }\OtherTok{\textless{}{-}}\NormalTok{ datos[,}\StringTok{"Y47"}\NormalTok{]}

\CommentTok{\# Guardamos el número de datos}
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(Y)}
\end{Highlighting}
\end{Shaded}

\hypertarget{relaciuxf3n-entre-variable-explicativa-y-variable-respuesta}{%
\section{1) Relación entre variable explicativa y variable
respuesta}\label{relaciuxf3n-entre-variable-explicativa-y-variable-respuesta}}

En primer lugar, calculamos la covarianza entre las variables. Debemos
tener en cuenta que R la calcula como una 'cuasi'covarianza, es decir,
dividiendo entre \(n-1\) en lugar de entre \(n\). Para corregirlo,
multiplicamos por \(n-1\) y dividimos entre \(n\), aunque también
mostraremos el valor original.

y el coeficiente de correlación de los datos, con el objetivo de ver si
existe relación lineal entre las variables.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{covar }\OtherTok{=} \FunctionTok{cov}\NormalTok{(X,Y)}\SpecialCharTok{*}\NormalTok{(n}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{/}\NormalTok{n; covar           }\CommentTok{\# Covarianza}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -8.275695
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cov}\NormalTok{(X,Y)                                  }\CommentTok{\# Cuasicovarianza}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -8.345238
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(X, Y)                                 }\CommentTok{\# Coeficiente de correlación}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.9506962
\end{verbatim}

Como vemos, tanto la covarianza como la correlación son negativas. En el
caso de la covarianza, esta no nos indica una medida fiable de la
relación entre los datos, ya que depende de la escala de los datos. Sin
embargo, la correlación, con un valor de -0.95 nos da a entender una
relación de proporcionalidad inversa entre X e Y, que podremos
corroborar posteriormente al ver el diagrama de dispersión.

A continuación hallamos el vector de medias o centro de gravedad
aplicando \texttt{mean} en ambas variables:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mX }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(X)}
\NormalTok{mY }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(Y)}
\end{Highlighting}
\end{Shaded}

Y con la siguiente función generamos el diagrama de dispersión de los
datos:

\includegraphics{divideyvenceras_files/figure-latex/dispersion-1.pdf}
Fácilmente observamos que la nube de puntos toma una forma descendente,
lo cuál encaja con el hecho de que la correlación entre X e Y sea
negativa. También vemos que los datos están, de forma aproximada,
uniformemente alineados en torno a una forma rectilínea. Todo esto
motiva el establecimiento de un modelo lineal para la relación entre
ambas variables. Recordemos que los modelos lineales son de la forma: \[
Y = \beta_0 + \beta_1X + \epsilon
\] Ajustamos entonces este modelo a nuestros datos mediante la función
lm:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Y}\SpecialCharTok{\textasciitilde{}}\NormalTok{X); modelo}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Y ~ X)
## 
## Coefficients:
## (Intercept)            X  
##       4.184       -1.023
\end{verbatim}

y obtenemos un intercepto \(\beta_0 = 4.184\) y una pendiente de
\(\beta_1 = -1.023\), lo cuál concuerda con lo observado anteriormente
en la nube de puntos.

En los siguientes ejercicios, analizaremos más en profundidad este
modelo. Además, lo validaremos frente a otros modelos como los
polinómicos o los no paramétricos.

\hypertarget{ejercicio-2}{%
\subsection{Ejercicio 2}\label{ejercicio-2}}

\hypertarget{estimaciuxf3n-puntual-a-mano}{%
\subsubsection{Estimación puntual a
mano}\label{estimaciuxf3n-puntual-a-mano}}

Para la estimación puntual de los parámetros intercepto \(\beta_0\),
pendiente \(beta_1\) y varianza del error \(\sigma^2\) podemos aplicar
directamente las fórmulas obtenidas en la parte teórica de la
asignatura:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{var.X }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(X)}\SpecialCharTok{*}\NormalTok{(n}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{/}\NormalTok{n}
\NormalTok{beta0.gorro }\OtherTok{=}\NormalTok{ mY }\SpecialCharTok{{-}}\NormalTok{ covar}\SpecialCharTok{*}\NormalTok{mX}\SpecialCharTok{/}\NormalTok{var.X; beta0.gorro}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.184343
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{beta1.gorro }\OtherTok{=}\NormalTok{ covar}\SpecialCharTok{/}\NormalTok{var.X; beta1.gorro}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1.022889
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{var.error }\OtherTok{=} \FunctionTok{sum}\NormalTok{((Y }\SpecialCharTok{{-}}\NormalTok{ beta0.gorro }\SpecialCharTok{{-}}\NormalTok{ beta1.gorro}\SpecialCharTok{*}\NormalTok{X)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{/}\NormalTok{(n}\DecValTok{{-}2}\NormalTok{); var.error}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.916048
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sd.error }\OtherTok{=} \FunctionTok{sqrt}\NormalTok{(var.error); sd.error}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.957104
\end{verbatim}

\hypertarget{estimaciuxf3n-puntual-automuxe1tica}{%
\subsubsection{Estimación puntual
automática}\label{estimaciuxf3n-puntual-automuxe1tica}}

De manera alternativa, podemos obtenrlas a partir del propio modelo
creado anteriomente por \(\mathbb{R}\):

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo    }\CommentTok{\# Información del modelo}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Y ~ X)
## 
## Coefficients:
## (Intercept)            X  
##       4.184       -1.023
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo}\SpecialCharTok{$}\NormalTok{coefficients         }\CommentTok{\# beta0 gorro y beta1 gorro}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)           X 
##    4.184343   -1.022889
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# En modelo$residuals están los residuos}
\FunctionTok{sum}\NormalTok{(modelo}\SpecialCharTok{$}\NormalTok{residuals}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{/}\NormalTok{(n}\DecValTok{{-}2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.916048
\end{verbatim}

\includegraphics{divideyvenceras_files/figure-latex/dispersionReg-1.pdf}

Incluimos también una gráfica adicional usando la librería
\emph{ggplot2} e incluyendo la región o intervalo de confianza para los
datos al nivel del 99\%:
\includegraphics{divideyvenceras_files/figure-latex/dispersionRegGGPLOT-1.pdf}

\hypertarget{ejercicio-3}{%
\subsection{Ejercicio 3}\label{ejercicio-3}}

\textit{Calcula los intervalos de confianza para los parámetros del modelo de nivel 99%.
Interpreta los resultados obtenidos.} En primer lugar, establecemos el
nivel de significación \(\alpha\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alfa }\OtherTok{\textless{}{-}} \DecValTok{1} \SpecialCharTok{{-}} \FloatTok{0.99}
\end{Highlighting}
\end{Shaded}

A continuación, hallamos los intervalos para

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{beta0.cuantil }\OtherTok{\textless{}{-}} \FunctionTok{qt}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{alfa}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}2}\NormalTok{); beta0.cuantil}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.618137
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{beta0.extremoinferior }\OtherTok{\textless{}{-}}\NormalTok{ beta0.gorro }\SpecialCharTok{{-}}\NormalTok{ beta0.cuantil }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(var.error }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{/}\NormalTok{n }\SpecialCharTok{+}\NormalTok{ mX}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{(n}\SpecialCharTok{*}\NormalTok{var.X)))}
\NormalTok{beta0.extremosuperior }\OtherTok{\textless{}{-}}\NormalTok{ beta0.gorro }\SpecialCharTok{+}\NormalTok{ beta0.cuantil }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(var.error }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{/}\NormalTok{n }\SpecialCharTok{+}\NormalTok{ mX}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{(n}\SpecialCharTok{*}\NormalTok{var.X)))}
\NormalTok{beta0.IC }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(beta0.extremoinferior, beta0.extremosuperior); beta0.IC}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.771852 4.596833
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{beta1.cuantil }\OtherTok{\textless{}{-}}\NormalTok{ beta0.cuantil}
\NormalTok{beta1.extremoinferior }\OtherTok{\textless{}{-}}\NormalTok{ beta1.gorro }\SpecialCharTok{{-}}\NormalTok{ beta1.cuantil}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(var.error}\SpecialCharTok{/}\NormalTok{(var.X }\SpecialCharTok{*}\NormalTok{ n))}
\NormalTok{beta1.extremosuperior }\OtherTok{\textless{}{-}}\NormalTok{ beta1.gorro }\SpecialCharTok{+}\NormalTok{ beta1.cuantil}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(var.error}\SpecialCharTok{/}\NormalTok{(var.X }\SpecialCharTok{*}\NormalTok{ n))}
\NormalTok{beta1.IC }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(beta1.extremoinferior, beta1.extremosuperior); beta1.IC}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1.1033105 -0.9424673
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{var.error.cuantilinferior }\OtherTok{\textless{}{-}} \FunctionTok{qchisq}\NormalTok{(alfa}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}2}\NormalTok{)}
\NormalTok{var.error.cuantilsuperior }\OtherTok{\textless{}{-}} \FunctionTok{qchisq}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{alfa}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}2}\NormalTok{)}
\NormalTok{var.error.extremoinferior }\OtherTok{\textless{}{-}}\NormalTok{ (n}\DecValTok{{-}2}\NormalTok{)}\SpecialCharTok{*}\NormalTok{var.error}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{var.error.cuantilsuperior}
\NormalTok{var.error.extremosuperior }\OtherTok{\textless{}{-}}\NormalTok{ (n}\DecValTok{{-}2}\NormalTok{)}\SpecialCharTok{*}\NormalTok{var.error}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{var.error.cuantilinferior}
\NormalTok{var.error.IC }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(var.error.extremoinferior, var.error.extremosuperior); var.error.IC}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.6138273 1.2048240
\end{verbatim}

Pero también podemos utilizar las funciones de R para hacerlo de forma
automática: - IC para beta0 y beta1 asumiendo que la varianza es
desconocida

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{confint}\NormalTok{(modelo, }\AttributeTok{level=}\FloatTok{0.99}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                 0.5 %     99.5 %
## (Intercept)  3.771852  4.5968334
## X           -1.103311 -0.9424673
\end{verbatim}

No hay una automatización del cálculo de la varianza del error

\hypertarget{ejercicio-4}{%
\subsection{Ejercicio 4}\label{ejercicio-4}}

\textit{Realiza los contrates de significación asociados al intercepto y a la pendiente del
modelo de regresión considerado. Interpreta los resultados obtenidos. En base a
los resultados obtenidos, ¿tendría sentido considerar otro modelo más sencillo?}
A continuación, realizaremos los contrastes de significación sobre el
modelo con el objetivo de determinar si el modelo se podría simplificar
a uno con menos variables o no. En primer lugar, realizaremos el
contraste de forma manual a partir de los estadísticos de contraste
basado en el pivote de la estimaciones puntuales previas:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Contraste de significacion para beta0}
\NormalTok{beta0.t }\OtherTok{\textless{}{-}} \FunctionTok{abs}\NormalTok{(beta0.gorro) }\SpecialCharTok{/}\NormalTok{ (}\FunctionTok{sqrt}\NormalTok{(var.error }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{/}\NormalTok{n }\SpecialCharTok{+}\NormalTok{ mX}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{(n}\SpecialCharTok{*}\NormalTok{var.X)))); beta0.t}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 26.55861
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{beta1.t }\OtherTok{\textless{}{-}} \FunctionTok{abs}\NormalTok{(beta1.gorro) }\SpecialCharTok{/}\NormalTok{ (sd.error }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n}\SpecialCharTok{*}\NormalTok{var.X)); beta1.t}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 33.30029
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Rechazamos la hipótesis nula de que el modelo tiene origen de 0}
\NormalTok{beta0.t }\SpecialCharTok{\textgreater{}}\NormalTok{ beta0.cuantil }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Rechazamos la hipótesis nula de que el modelo no tiene pendiente}
\NormalTok{beta1.t }\SpecialCharTok{\textgreater{}}\NormalTok{ beta1.cuantil}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# El p{-}valor es 0 {-}{-}\textgreater{} La hipótesis nula es falsa para cualquier nivel de signif. {-}{-}\textgreater{} El modelo tiene un intercepto distinto de 0}
\NormalTok{beta0.pvalor }\OtherTok{=} \FunctionTok{dt}\NormalTok{(beta0.t, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}2}\NormalTok{); beta0.pvalor}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.508369e-51
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# El p{-}valor es 0 {-}{-}\textgreater{} La hipótesis nula es falsa para cualquier nivel de signif. {-}{-}\textgreater{} El modelo tiene una pendiente distinta de 0}
\NormalTok{beta1.pvalor }\OtherTok{=} \FunctionTok{dt}\NormalTok{(beta1.t, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}2}\NormalTok{); beta1.pvalor}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.237751e-61
\end{verbatim}

De esto deducimos que existen pruebas estadísticamente significativas de
que \(\beta_0 \neq 0\), lo cuál nos indica que el intercepto es distinto
de 0. Por otro lado, también existen pruebas de \(\beta_1 \neq 0\), de
dónde deducimos que realmente la variable explicativa influye en la
variable respuesta.

Alternativamente, podemos obtener los valores de estos dos contrastes de
significación y su p-valor a partir de los datos presentes en el modelo
de R. Para esto, usaremos la función summary:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(modelo)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Y ~ X)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.76465 -0.72493  0.00685  0.71260  2.20924 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  4.18434    0.15755   26.56   <2e-16 ***
## X           -1.02289    0.03072  -33.30   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.9571 on 118 degrees of freedom
## Multiple R-squared:  0.9038, Adjusted R-squared:  0.903 
## F-statistic:  1109 on 1 and 118 DF,  p-value: < 2.2e-16
\end{verbatim}

En concreto, los valores relevantes son el t-value y el
Pr(\textgreater\textbar t\textbar) de las filas (Intercept) y X que se
corresponden al valor observado del estadístico observado y su p-valor
en el contraste sobre el intercepto \(\beta_0\) y la pendiente
\(\beta_1\). Obtenemos los mismos datos que en el cálculo manual.

En base a los resultados obtenidos anteriormente, decidimos no
simplificar más nuestro modelo y continuar realizando regresión lineal.

\hypertarget{ejercicio-5}{%
\subsection{Ejercicio 5}\label{ejercicio-5}}

\textit{Si consideramos que la variable 𝑋𝑋 toma 3 nuevos valores: 2, 4 y 6 unidades, proporciona intervalos de predicción e intervalos de confianza para la media condicionada de la variable 𝑌𝑌. Interpreta los resultados obtenidos.}

En este apartado, consideramos 3 nuevos valores para la variable
explicativa \(X = 2, 4, 6\). Para obtener intervalos de confianza para
la media de Y condicionada a estos valores y de predicción, es necesario
comprobar primero que estos datos están dentro del rango de observación
de X. Esto es debido a que no sabemos como se comporta el modelo fuera
del rango observado, y nuestro objetivo es predecir y no extrapolar.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nuevosValores }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{6}\NormalTok{)}
\CommentTok{\# El rango está contenido}
\FunctionTok{min}\NormalTok{(X) }\SpecialCharTok{\textless{}} \FunctionTok{min}\NormalTok{(nuevosValores) }\SpecialCharTok{\&\&} \FunctionTok{max}\NormalTok{(X) }\SpecialCharTok{\textgreater{}} \FunctionTok{max}\NormalTok{(nuevosValores)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Construimos un data.frame  con los nuevos datos ya que predict necesita este formato para sus predicciones}
\NormalTok{nuevosDatos }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\StringTok{"X"} \OtherTok{=}\NormalTok{ nuevosValores)}
\end{Highlighting}
\end{Shaded}

Habiendo realizado esta comprobación, ya podemos obtener los intervalos
utilizando la función predict sobre el modelo de R. Obtendremos ambos
intervalos para los niveles de significación 0.95 y 0.99. ((TODO:
REVISAR, ESTOS ESTÁN BIEN PERO DEBERÍAN SER CONSISTENTES CON OTRAS
PARTES DONDE COJAMOS ALFAS ARBITRARIOS))

En primer lugar, pasando el argumento
\(\texttt{interval = "confidence"}\) obtenemos los asociados a la media
condicionada.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{predict}\NormalTok{(modelo, }\AttributeTok{newdata =}\NormalTok{ nuevosDatos, }\AttributeTok{interval =} \StringTok{"confidence"}\NormalTok{, }\AttributeTok{level=}\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           fit       lwr        upr
## 1  2.13856482  1.917271  2.3598582
## 2  0.09278705 -0.080999  0.2665731
## 3 -1.95299072 -2.155557 -1.7504246
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{predict}\NormalTok{(modelo, }\AttributeTok{newdata =}\NormalTok{ nuevosDatos, }\AttributeTok{interval =} \StringTok{"confidence"}\NormalTok{, }\AttributeTok{level=}\FloatTok{0.99}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           fit        lwr        upr
## 1  2.13856482  1.8459908  2.4311389
## 2  0.09278705 -0.1369772  0.3225513
## 3 -1.95299072 -2.2208054 -1.6851761
\end{verbatim}

Y para obtener los intervalos de predicción, los cuáles serán más
amplios que los anteriores, pasamos el argumento
\(\texttt{interval = "prediction"}\)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{predict}\NormalTok{(modelo, }\AttributeTok{newdata =}\NormalTok{ nuevosDatos, }\AttributeTok{interval =} \StringTok{"prediction"}\NormalTok{, }\AttributeTok{level=}\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           fit        lwr         upr
## 1  2.13856482  0.2303633  4.04676635
## 2  0.09278705 -1.8104901  1.99606420
## 3 -1.95299072 -3.8591112 -0.04687022
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{predict}\NormalTok{(modelo, }\AttributeTok{newdata =}\NormalTok{ nuevosDatos, }\AttributeTok{interval =} \StringTok{"prediction"}\NormalTok{, }\AttributeTok{level=}\FloatTok{0.99}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           fit        lwr       upr
## 1  2.13856482 -0.3842867 4.6614163
## 2  0.09278705 -2.4235539 2.6091280
## 3 -1.95299072 -4.4730909 0.5671095
\end{verbatim}

\end{document}
